insert into tarefa (id, descricao, finalizado, data_Finalizacao) values (1, 'Teste 1', true, '2017-06-01')
insert into tarefa (id, descricao, finalizado, data_Finalizacao) values (2, 'Teste 2', true, '2017-06-01')
insert into tarefa (id, descricao, finalizado, data_Finalizacao) values (3, 'Teste 3', false, '2017-06-01')
insert into tarefa (id, descricao, finalizado, data_Finalizacao) values (4, 'Teste 4', false, '2017-06-01')
insert into tarefa (id, descricao, finalizado, data_Finalizacao) values (5, 'Teste 5', true, '2017-06-01')
